# Generated by Django 4.2.6 on 2024-12-06 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lobby',
            old_name='code',
            new_name='lobby_id',
        ),
        migrations.RemoveField(
            model_name='lobby',
            name='file',
        ),
        migrations.RemoveField(
            model_name='lobby',
            name='players',
        ),
        migrations.AddField(
            model_name='lobby',
            name='status',
            field=models.CharField(choices=[('waiting', 'Waiting'), ('active', 'Active'), ('completed', 'Completed')], default='waiting', max_length=20),
        ),
    ]
