# Generated by Django 4.2.6 on 2024-12-06 17:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quiz', '0002_rename_code_lobby_lobby_id_remove_lobby_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lobby',
            name='players',
            field=models.ManyToManyField(blank=True, related_name='joined_lobbies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='lobby',
            name='host',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hosted_lobbies', to=settings.AUTH_USER_MODEL),
        ),
    ]
